name: dooadex_constants
description: A useful constants
version: 0.0.8
homepage: https://github.com/Doohyeon-Kim/dooadex-constants.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
